version: '3'
services:
 my-app:
  environment:
    GOMEMLIMIT: "270MiB"
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
  deploy:
    resources:
      limits:
       memory: 300M